---
kind: Namespace
apiVersion: v1
metadata:
  name: miniloops

---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: miniloops-operator
    app.kubernetes.io/version: v0.0.1
  name: miniloops-operator
  namespace: miniloops
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: miniloops-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: miniloops-operator
        app.kubernetes.io/version: v0.0.1
    spec:
      containers:
      - name: operator
        image: clevertelemetry/miniloops:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
...